### ISSUE TITLE
I can't access global vars of caddy (ex:query parameter)

### ISSUE THREAD

**Issue by yharby** [neodyme-labs/influx_log#1]
I can access the {http.request.uri.query.access_token} outside the influx_log, but i can't add it as a tag.
```
log {
               output influx_log {
                       token mytoken
                       org myorg
                       bucket my-bucket
                       measurement l1
                       tags {
                               hostname {request_host}
                               remote_ip {request_remote_ip}
                               access_token {http.request.uri.query.access_token}  ## The Problem is here ##
                       }
                       host http://localhost:8086
               }
       }
```

**Comment by kilimnik** [comment]
Currently this is not possible. To do this, we would need to get an instance of the `Replacer` for each request. But that is currently not possible via Caddy. 

There is a hack to do this though. You could add `header access_token "{http.request.uri.query.access_token}"` to your config. That way you have the `access_token` query param singled out and can access it in the tags via `access_token {resp_headers_Access_token}`.

I will have to think about a better solution though

**Comment by yharby** [comment]
Thank you @kilimnik 
I will try it with headers

**Comment by yharby** [comment]
It's now working from the headers, but I have another problem because the token has hyphen " - " in between and InfluxDB reads it as separated tags … I think?
Do I need a regex or something else to remove first and last “[ ]” to make InfluxDB reading it as a one variable and not splitting into two? 

![Screenshot 2022-11-19 at 14-53-06 Data Explorer InfluxDB](https://user-images.githubusercontent.com/13020265/202927783-0c36f7e6-5a09-4039-be92-114332f280bd.png)

**Comment by kilimnik** [comment]
The problem is that there are quotation marks in the header. The query builder does not escape those.
I already opened an issue over there https://github.com/influxdata/influxdb/issues/23896.

You can solve this by using the script editor and escaping the quotation marks with a backslash. Like this:
```
...
  |> filter(fn: (r) => r["access_token"] == "[\"mapsaudi...\"]")
...
```
